import {BaseModel} from './base.model'

export class Accessoire extends BaseModel{
    id: Number
    acs_part: String
    acs_desc1: String
    acs_desc2: String
    acs_um: String
    acs_draw: String
    acs_prod_line: String
    acs_group: String
    acs_part_type: String
    acs_status: String
    acs_abc: String
    acs_iss_pol: Boolean
    acs_phantom: Boolean
    acs_loc: String
    acs_abc_amt: Number
    acs_avg_int: Number
    acs_cyc_int: Number
    acs_ms: Boolean
    acs_plan_ord: Boolean
    acs_mrp: Boolean
    acs_ord_pol: String
    acs_ord_qty: Number
    acs_ord_per: Number
    acs_sfty_stk: Number
    acs_sfty_time: Number
    acs_rop: Number
    acs_buyer: String
    acs_vend: String
    acs_pm_code: String
    acs_mfg_lead: Number
    acs_pur_lead: Number
    acs_insp_rqd: Boolean
    acs_insp_lead: Number
    acs_cum_lead: Number
    acs_ord_min: Number
    acs_ord_max: Number
    acs_ord_mult: Number
    acs_yield_pct: Number
    acs_setup: Number
    acs_setup_ll: Number
    acs_run_ll: Number
    acs_run: Number
    acs_price: Number
    acs_pur_price: Number
    acs_marge: Number
    acs_sales_price: Number
    acs_xmtl_tl: Number
    acs_xlbr_tl: Number
    acs_xbdn_tl: Number
    acs_xsub_tl: Number
    acs_xmtl_ll: Number
    acs_xlbr_ll: Number
    acs_xbdn_ll: Number
    acs_xsub_ll: Number
    acs_xtot_cur: Number
    acs_cur_date: Date
    acs_xmtl_stdtl: Number
    acs_xlbr_stdtl: Number
    acs_xbdn_stdtl: Number
    acs_xsub_stdtl: Number
    acs_xtot_std: Number
    acs_std_date: Date
    acs_ll_code: Number
    acs_abc_qty: Number
    acs_routing: String
    acs_lot_ser: String
    acs_timefence: Number
    acs_xmtl_stdll: Number
    acs_xlbr_stdll: Number
    acs_xbdn_stdll: Number
    acs_xsub_stdll: Number
    acs_rev: String
    acs_last_eco: Date
    acs_qc_lead: Number
    acs_auto_lot: Boolean
    acs_assay: Number
    acs_batch: Number
    acs_user3: String
    acs_user2: String
    acs_user1: String
    acs_net_wt: Number
    acs_net_wt_um: String
    acs_size: Number
    acs_size_um: String
    acs_taxable: Boolean
    acs_taxc: String
    acs_rollup: Boolean
    acs_xovh_ll: Number
    acs_xovh_tl: Number
    acs_xovh_stdll: Number
    acs_xovh_stdtl: Number
    acs_site: String
    acs_shelflife: Number
    acs_critical: Boolean
    acs_sngl_lot: Boolean
    acs_upc: String
    acs_hazard: String
    acs_added: Date
    acs_length: Number
    acs_height: Number
    acs_width: Number
    acs_dim_um: String
    acs_pkg_code: String
    acs_network: String
    acs_fr_class: String
    acs_spec_hdlg: String
    acs_bom_code: String
    acs_loc_type: String
    acs_transtype: String
    acs_warr_cd: String
    acs_pvm_days: Number
    acs_isb: Boolean
    acs_mttr: Number
    acs_mtbf: Number
    acs_svc_type: String
    acs_svc_group: String
    acs_ven_warr: Boolean
    acs_fru: Boolean
    acs_mfg_mttr: Number
    acs_mfg_mtbf: Number
    acs_sttr: Number
    acs_origin: String
    acs_tariff: String
    acs_sys_type: String
    acs_inst_call: Boolean
    acs_cover: String
    acs_unit_isb: Boolean
    acs_article: String
    acs_ll_drp: Number
    acs_po_site: String
    acs_ship_wt: Number
    acs_ship_wt_um: String
    acs_userid: String
    acs_mod_date: Date
    acs_comm_code: String
    acs_dea: Boolean
    acs_formula: Boolean
    acs_obs_date: Date
    acs_pvm_bom: String
    acs_pvm_route: String
    acs_pvm_um: String
    acs_rp_bom: String
    acs_rp_route: String
    acs_rp_vendor: String
    acs_rctpo_status: String
    acs_rollup_id: String
    acs_spec_grav: Number
    acs_joint_type: String
    acs_mfg_pct: Number
    acs_pur_pct: Number
    acs_drp_pct: Number
    acs_pou_code: String
    acs_wks_avg: Number
    acs_wks_max: Number
    acs_wks_min: Number
    acs_pick_logic: Number
    acs_fiscal_class: String
    acs_dsgn_grp: String
    acs_drwg_loc: String
    acs_ecn_rev: String
    acs_drwg_size: String
    acs_model: String
    acs_repairable: Boolean
    acs_rctwo_status: String
    acs_rctpo_active: Boolean
    acs_lot_grp: String
    acs_rctwo_active: Boolean
    acs_break_cat: String
    acs_fsc_code: String
    acs_trace_active: Boolean
    acs_trace_detail: Boolean
    acs_pm_mrp: Boolean
    acs_ins_call_type: String
    acs_ins_bom: String
    acs_ins_route: String
    acs_promo: String
    acs_meter_interval: Number
    acs_meter_um: String
    acs_wh: Boolean
    acs_btb_type: String
    acs_cfg_type: String
    acs_app_owner: String
    acs_op_yield: String
    acs_run_seq1: String
    acs_run_seq2: String
    acs_atp_enforcement: String
    acs_atp_family: Boolean
    acs_domain: String
}