export class BaseModel {
    id: Number
    chr01: String
    chr02: String
    chr03: String
    chr04: String
    chr05: String
    int01: Number
    int02: Number
    int03: Number
    int04: Number
    int05: Number
    dec01: Number
    dec02: Number
    dec03: Number
    dec04: Number
    dec05: Number
    bool01: Boolean
    bool02: Boolean
    bool03: Boolean
    bool04: Boolean
    bool05: Boolean
    date01:  String
    date02:  String
    date03:  String
    date04:  String
    date05:  String
    created_ip_adr: String
    last_modified_ip_adr: String
    created_by: String
    last_modified_by: String
}
