
import { BaseModel } from "./base.model"

export class DailySales extends BaseModel {

    id: Number
    ds_nbr: String
    ds_cust: String
    ds_ship: String
    ds_category: String
    ds_ord_date: String
    ds_req_date: String
    ds_due_date: String
    ds_rmks: String
    ds_cr_terms: String
    ds_fob: String
    ds_po: String
    ds_shipvia: String
    ds_partial: Boolean
    ds_conf: Boolean
    ds_print_so: Boolean
    ds_inv_nbr: String
    ds_pr_list: String
    ds_xslspsn: String
    ds_source: String
    ds_xcomm_pct: Number
    ds_cr_card: String
    ds_print_pl: Boolean
    ds_cr_init: String
    ds_stat: String
    ds__qad01: Number
    ds__qad02: Number
    ds__qad03: Number
    ds_disc_pct: Number
    ds_tax_pct: Number
    ds_prepaid: Number
    ds_to_inv: Boolean
    ds_invoiced: Boolean
    ds_ar_acct: String
    ds_ar_cc: String
    ds_inv_date: String
    ds_ship_date: String
    ds_taxable: Boolean
    ds_cmtindx: Number
    ds__qad04: Number
    ds_user1: String
    ds_user2: String
    ds_curr: String
    ds_ex_rate: Number
    ds_lang: String
    ds_type: String
    ds_conf_date: String
    ds_rev: Number
    ds_bol: String
    ds__qad05: Number
    ds_pst: Boolean
    ds_fst_id: String
    ds_trl1_amt: Number
    ds_trl1_cd: String
    ds_trl2_amt: Number
    ds_trl2_cd: String
    ds_trl3_amt: Number
    ds_trl3_cd: String
    ds_weight: Number
    ds_weight_um: String
    ds_size: Number
    ds_size_um: String
    ds_cartons: Number
    ds_site: String
    ds_pst_id: String
    ds_cncl_date: String
    ds_quote: String
    ds_taxc: String
    ds__chr01: String
    ds__chr02: String
    ds__chr03: String
    ds__chr04: String
    ds__chr05: String
    ds__chr06: String
    ds__chr07: String
    ds__chr08: String
    ds__chr09: String
    ds__chr10: String
    ds__dte01: String
    ds__dte02: String
    ds__dec01: Number
    ds__dec02: Number
    ds__log01: Boolean
    ds_credit: Boolean
    ds_inv_cr: String
    ds_project: String
    ds_channel: String
    ds_pst_pct: Number
    ds_fr_list: String
    ds_fr_terms: String
    ds_slspsn: String
    ds_comm_pct: Number
    ds_inv_mthd: String
    ds_fix_rate: Boolean
    ds_ent_ex: Number
    ds_bill: String
    ds_print_bl: Boolean
    ds_userid: String
    ds_tax_date: String
    ds_fsm_type: String
    ds_conrep: String
    ds_bank: String
    ds_tax_env: String
    ds_sched: Boolean
    ds_fr_min_wt: Number
    ds_pr_list2: String
    ds_tax_usage: String
    ds_sa_nbr: String
    ds_fix_pr: Boolean
    ds_sch_mthd: String
    ds_pricing_dt: String
    ds_priced_dt: String
    ds_ca_nbr: String
    ds_eng_code: String
    ds_fcg_code: String
    ds_ship_eng: Boolean
    ds_crprlist: String
    ds__qadc01: String
    ds__qadc02: String
    ds__qadc03: String
    ds__qadc04: String
    ds__qadc05: String
    ds__qadl01: Boolean
    ds__qadl02: Boolean
    ds_incl_iss: Boolean
    ds__qadi01: Number
    ds__qadi02: Number
    ds__qadi03: Number
    ds__qadd01: Number
    ds__qadd02: Number
    ds__qadd03: Number
    ds__qadt01: String
    ds__qadt02: String
    ds__qadt03: String
    ds_auth_days: Number
    ds_cum_acct: Boolean
    ds_merge_rss: Boolean
    ds_ship_cmplt: Number
    ds_bump_all: Boolean
    ds_primary: Boolean
    ds_cust_po: String
    ds_secondary: Boolean
    ds_ship_po: String
    ds_ex_rate2: Number
    ds_ex_ratetype: String
    ds_div: String
    ds_exru_seq: Number
    ds_app_owner: String
    ds_ar_sub: String
    ds_seq_order: Boolean
    ds_inc_in_rss: Boolean
    ds_firm_seq_days: Number
    ds_prep_tax: Number
    ds__qadl04: Boolean
    ds_custref_val: Boolean
    ds_consignment: Boolean
    ds_max_aging_days: Number
    ds_consign_loc: String
    ds_intrans_loc: String
    ds_auto_replenish: Boolean
    ds_revenue: String
    ds_fsaccr_acct: String
    ds_fsaccr_sub: String
    ds_fsaccr_cc: String
    ds_fsdef_acct: String
    ds_fsdef_sub: String
    ds_fsdef_cc: String
    ds_manual_fr_terms: Boolean
    ds_domain: String
    oid_ds_mstr: Number
    ds_req_time: String
    ds_amt: Number
    ds_tax_amt : Number

}
