import {BaseModel} from './base.model'

export class Glasses extends BaseModel{
    id: Number
    gls_part: String
    gls_desc1: String
    gls_desc2: String
    gls_um: String
    gls_draw: String
    gls_prod_line: String
    gls_group: String
    gls_part_type: String
    gls_status: String
    gls_abc: String
    gls_iss_pol: Boolean
    gls_phantom: Boolean
    gls_loc: String
    gls_abc_amt: Number
    gls_avg_int: Number
    gls_cyc_int: Number
    gls_ms: Boolean
    gls_plan_ord: Boolean
    gls_mrp: Boolean
    gls_ord_pol: String
    gls_ord_qty: Number
    gls_ord_per: Number
    gls_sfty_stk: Number
    gls_sfty_time: Number
    gls_rop: Number
    gls_buyer: String
    gls_vend: String
    gls_pm_code: String
    gls_mfg_lead: Number
    gls_pur_lead: Number
    gls_insp_rqd: Boolean
    gls_insp_lead: Number
    gls_cum_lead: Number
    gls_ord_min: Number
    gls_ord_max: Number
    gls_ord_mult: Number
    gls_yield_pct: Number
    gls_setup: Number
    gls_setup_ll: Number
    gls_run_ll: Number
    gls_run: Number
    gls_price: Number
    gls_pur_price: Number
    gls_xmtl_tl: Number
    gls_xlbr_tl: Number
    gls_xbdn_tl: Number
    gls_xsub_tl: Number
    gls_xmtl_ll: Number
    gls_xlbr_ll: Number
    gls_xbdn_ll: Number
    gls_xsub_ll: Number
    gls_xtot_cur: Number
    gls_cur_date: Date
    gls_xmtl_stdtl: Number
    gls_xlbr_stdtl: Number
    gls_xbdn_stdtl: Number
    gls_xsub_stdtl: Number
    gls_xtot_std: Number
    gls_std_date: Date
    gls_ll_code: Number
    gls_abc_qty: Number
    gls_routing: String
    gls_lot_ser: String
    gls_timefence: Number
    gls_xmtl_stdll: Number
    gls_xlbr_stdll: Number
    gls_xbdn_stdll: Number
    gls_xsub_stdll: Number
    gls_rev: String
    gls_last_eco: Date
    gls_qc_lead: Number
    gls_auto_lot: Boolean
    gls_assay: Number
    gls_batch: Number
    gls_user3: String
    gls_user2: String
    gls_user1: String
    gls_net_wt: Number
    gls_net_wt_um: String
    gls_size: Number
    gls_size_um: String
    gls_taxable: Boolean
    gls_taxc: String
    gls_rollup: Boolean
    gls_xovh_ll: Number
    gls_xovh_tl: Number
    gls_xovh_stdll: Number
    gls_xovh_stdtl: Number
    gls_site: String
    gls_shelflife: Number
    gls_critical: Boolean
    gls_sngl_lot: Boolean
    gls_upc: String
    gls_hazard: String
    gls_added: Date
    gls_length: Number
    gls_height: Number
    gls_width: Number
    gls_dim_um: String
    gls_pkg_code: String
    gls_network: String
    gls_fr_class: String
    gls_spec_hdlg: String
    gls_bom_code: String
    gls_loc_type: String
    gls_transtype: String
    gls_warr_cd: String
    gls_pvm_days: Number
    gls_isb: Boolean
    gls_mttr: Number
    gls_mtbf: Number
    gls_svc_type: String
    gls_svc_group: String
    gls_ven_warr: Boolean
    gls_fru: Boolean
    gls_mfg_mttr: Number
    gls_mfg_mtbf: Number
    gls_cyl_beging: Number
    gls_cyl_end: Number
    gls_sph_beging: Number
    gls_sph_end: Number
    gls_add_beging: Number
    gls_add_end:  Number
    gls_prisme:  Number
    gls_base:  Number
    gls_sttr: Number
    gls_origin: String
    gls_tariff: String
    gls_sys_type: String
    gls_inst_call: Boolean
    gls_cover: String
    gls_unit_isb: Boolean
    gls_article: String
    gls_ll_drp: Number
    gls_po_site: String
    gls_ship_wt: Number
    gls_ship_wt_um: String
    gls_userid: String
    gls_mod_date: Date
    gls_comm_code: String
    gls_dea: Boolean
    gls_formula: Boolean
    gls_obs_date: Date
    gls_pvm_bom: String
    gls_pvm_route: String
    gls_pvm_um: String
    gls_rp_bom: String
    gls_rp_route: String
    gls_rp_vendor: String
    gls_rctpo_status: String
    gls_rollup_id: String
    gls_spec_grav: Number
    gls_joint_type: String
    gls_mfg_pct: Number
    gls_pur_pct: Number
    gls_drp_pct: Number
    gls_pou_code: String
    gls_wks_avg: Number
    gls_wks_max: Number
    gls_wks_min: Number
    gls_pick_logic: Number
    gls_fiscal_class: String
    gls_dsgn_grp: String
    gls_drwg_loc: String
    gls_ecn_rev: String
    gls_drwg_size: String
    gls_model: String
    gls_repairable: Boolean
    gls_rctwo_status: String
    gls_rctpo_active: Boolean
    gls_lot_grp: String
    gls_rctwo_active: Boolean
    gls_break_cat: String
    gls_fsc_code: String
    gls_trace_active: Boolean
    gls_trace_detail: Boolean
    gls_pm_mrp: Boolean
    gls_ins_call_type: String
    gls_ins_bom: String
    gls_ins_route: String
    gls_promo: String
    gls_meter_interval: Number
    gls_meter_um: String
    gls_wh: Boolean
    gls_btb_type: String
    gls_cfg_type: String
    gls_app_owner: String
    gls_op_yield: String
    gls_run_seq1: String
    gls_run_seq2: String
    gls_atp_enforcement: String
    gls_atp_family: Boolean
    gls_domain: String
}