import {BaseModel} from './base.model'

export class Item extends BaseModel{
    id: Number
    pt_part: String
    pt_desc1: String
    pt_desc2: String
    pt_um: String
    pt_draw: String
    pt_prod_line: String
    pt_group: String
    pt_part_type: String
    pt_status: String
    pt_abc: String
    pt_iss_pol: Boolean
    pt_phantom: Boolean
    pt_loc: String
    pt_abc_amt: Number
    pt_avg_int: Number
    pt_cyc_int: Number
    pt_ms: Boolean
    pt_plan_ord: Boolean
    pt_mrp: Boolean
    pt_ord_pol: String
    pt_ord_qty: Number
    pt_ord_per: Number
    pt_sfty_stk: Number
    pt_sfty_time: Number
    pt_rop: Number
    pt_buyer: String
    pt_vend: String
    pt_pm_code: String
    pt_mfg_lead: Number
    pt_pur_lead: Number
    pt_insp_rqd: Boolean
    pt_insp_lead: Number
    pt_cum_lead: Number
    pt_ord_min: Number
    pt_ord_max: Number
    pt_ord_mult: Number
    pt_yield_pct: Number
    pt_setup: Number
    pt_setup_ll: Number
    pt_run_ll: Number
    pt_run: Number
    pt_price: Number
    pt_pur_price: Number
    pt_sales_price: Number
    pt_marge: Number
    pt_xmtl_tl: Number
    pt_xlbr_tl: Number
    pt_xbdn_tl: Number
    pt_xsub_tl: Number
    pt_xmtl_ll: Number
    pt_xlbr_ll: Number
    pt_xbdn_ll: Number
    pt_xsub_ll: Number
    pt_xtot_cur: Number
    pt_cur_date: Date
    pt_xmtl_stdtl: Number
    pt_xlbr_stdtl: Number
    pt_xbdn_stdtl: Number
    pt_xsub_stdtl: Number
    pt_xtot_std: Number
    pt_std_date: Date
    pt_ll_code: Number
    pt_abc_qty: Number
    pt_routing: String
    pt_lot_ser: String
    pt_timefence: Number
    pt_xmtl_stdll: Number
    pt_xlbr_stdll: Number
    pt_xbdn_stdll: Number
    pt_xsub_stdll: Number
    pt_rev: String
    pt_last_eco: Date
    pt_qc_lead: Number
    pt_auto_lot: Boolean
    pt_assay: Number
    pt_batch: Number
    pt_user3: String
    pt_user2: String
    pt_user1: String
    pt_net_wt: Number
    pt_net_wt_um: String
    pt_size: Number
    pt_size_um: String
    pt_taxable: Boolean
    pt_taxc: String
    pt_rollup: Boolean
    pt_xovh_ll: Number
    pt_xovh_tl: Number
    pt_xovh_stdll: Number
    pt_xovh_stdtl: Number
    pt_site: String
    pt_shelflife: Number
    pt_critical: Boolean
    pt_sngl_lot: Boolean
    pt_upc: String
    pt_hazard: String
    pt_added: Date
    pt_length: Number
    pt_height: Number
    pt_width: Number
    pt_dim_um: String
    pt_pkg_code: String
    pt_network: String
    pt_fr_class: String
    pt_spec_hdlg: String
    pt_bom_code: String
    pt_loc_type: String
    pt_transtype: String
    pt_warr_cd: String
    pt_pvm_days: Number
    pt_isb: Boolean
    pt_mttr: Number
    pt_mtbf: Number
    pt_svc_type: String
    pt_svc_group: String
    pt_ven_warr: Boolean
    pt_fru: Boolean
    pt_mfg_mttr: Number
    pt_mfg_mtbf: Number
    pt_sttr: Number
    pt_origin: String
    pt_tariff: String
    pt_sys_type: String
    pt_inst_call: Boolean
    pt_cover: String
    pt_unit_isb: Boolean
    pt_article: String
    pt_ll_drp: Number
    pt_po_site: String
    pt_ship_wt: Number
    pt_ship_wt_um: String
    pt_userid: String
    pt_mod_date: Date
    pt_comm_code: String
    pt_dea: Boolean
    pt_formula: Boolean
    pt_obs_date: Date
    pt_pvm_bom: String
    pt_pvm_route: String
    pt_pvm_um: String
    pt_rp_bom: String
    pt_rp_route: String
    pt_rp_vendor: String
    pt_rctpo_status: String
    pt_rollup_id: String
    pt_spec_grav: Number
    pt_joint_type: String
    pt_mfg_pct: Number
    pt_pur_pct: Number
    pt_drp_pct: Number
    pt_pou_code: String
    pt_wks_avg: Number
    pt_wks_max: Number
    pt_wks_min: Number
    pt_pick_logic: Number
    pt_fiscal_class: String
    pt_dsgn_grp: String
    pt_drwg_loc: String
    pt_ecn_rev: String
    pt_drwg_size: String
    pt_model: String
    pt_repairable: Boolean
    pt_rctwo_status: String
    pt_rctpo_active: Boolean
    pt_lot_grp: String
    pt_rctwo_active: Boolean
    pt_break_cat: String
    pt_fsc_code: String
    pt_trace_active: Boolean
    pt_trace_detail: Boolean
    pt_pm_mrp: Boolean
    pt_ins_call_type: String
    pt_ins_bom: String
    pt_ins_route: String
    pt_promo: String
    pt_meter_interval: Number
    pt_meter_um: String
    pt_wh: Boolean
    pt_btb_type: String
    pt_cfg_type: String
    pt_app_owner: String
    pt_op_yield: String
    pt_run_seq1: String
    pt_run_seq2: String
    pt_atp_enforcement: String
    pt_atp_family: Boolean
    pt_domain: String
}