import { BaseModel } from "./base.model"

export class ProductLine extends BaseModel {
    id: Number
    pl_prod_line: String
    pl_desc: String
    pl_sls_acct: String
    pl_inv_acct: String
    pl_wip_acct: String
    pl_cog_acct: String
    pl_pur_acct: String
    pl_scrp_acct: String
    pl_dscr_acct: String
    pl_sls_cc: String
    pl_inv_cc: String
    pl_wip_cc: String
    pl_cog_cc: String
    pl_pur_cc: String
    pl_scrp_cc: String
    pl_dscr_cc: String
    pl_ppv_acct: String
    pl_ppv_cc: String
    pl_rcpt_acct: String
    pl_rcpt_cc: String
    pl_dsc_acct: String
    pl_dsc_cc: String
    pl_wvar_acct: String
    pl_wvar_cc: String
    pl_taxc: String
    pl_taxable: Boolean
    pl_user1: String
    pl_user2: String
    pl_pst: Boolean
    pl_esls_acct: String
    pl_esls_cc: String
    pl_group: String
    pl_division: String
    pl_cchg_acct: String
    pl_cchg_cc: String
    pl_userid: String
    pl_mod_date: String
    pl_cmtl_acct: String
    pl_cmtl_cc: String
    pl_clbr_acct: String
    pl_clbr_cc: String
    pl_cbdn_acct: String
    pl_cbdn_cc: String
    pl_covh_acct: String
    pl_covh_cc: String
    pl_csub_acct: String
    pl_csub_cc: String
    pl_apvr_acct: String
    pl_apvr_cc: String
    pl_apvu_acct: String
    pl_apvu_cc: String
    pl_ovh_acct: String
    pl_ovh_cc: String
    pl_mvar_acct: String
    pl_mvar_cc: String
    pl_mvrr_acct: String
    pl_mvrr_cc: String
    pl_svar_acct: String
    pl_svar_cc: String
    pl_svrr_acct: String
    pl_svrr_cc: String
    pl_cop_acct: String
    pl_cop_cc: String
    pl_flr_acct: String
    pl_flr_cc: String
    pl_rmar_acct: String
    pl_rmar_cc: String
    pl_fiscal_class: String
    pl_xvar_acct: String
    pl_xvar_cc: String
    pl_fslbr_acct: String
    pl_fsbdn_acct: String
    pl_fsexp_acct: String
    pl_fsexd_acct: String
    pl_fslbr_cc: String
    pl_fsbdn_cc: String
    pl_fsexp_cc: String
    pl_fsexd_cc: String
    pl_fsrc_inv_acct: String
    pl_fsrc_inv_cc: String
    pl_fscm_inv_acct: String
    pl_fscm_inv_cc: String
    pl_apvr_sub: String
    pl_apvu_sub: String
    pl_cbdn_sub: String
    pl_cchg_sub: String
    pl_clbr_sub: String
    pl_cmtl_sub: String
    pl_cog_sub: String
    pl_cop_sub: String
    pl_covh_sub: String
    pl_csub_sub: String
    pl_dscr_sub: String
    pl_dsc_sub: String
    pl_flr_sub: String
    pl_fsbdn_sub: String
    pl_fscm_inv_sub: String
    pl_fsexd_sub: String
    pl_fsexp_sub: String
    pl_fslbr_sub: String
    pl_fsrc_inv_sub: String
    pl_inv_sub: String
    pl_mvar_sub: String
    pl_mvrr_sub: String
    pl_ovh_sub: String
    pl_ppv_sub: String
    pl_pur_sub: String
    pl_rcpt_sub: String
    pl_rmar_sub: String
    pl_scrp_sub: String
    pl_sls_sub: String
    pl_svar_sub: String
    pl_svrr_sub: String
    pl_wip_sub: String
    pl_wvar_sub: String
    pl_xvar_sub: String
    pl_xfer_acct: String
    pl_xfer_sub: String
    pl_xfer_cc: String
    pl_fsdef_acct: String
    pl_fsdef_sub: String
    pl_fsdef_cc: String
    pl_fsaccr_acct: String
    pl_fsaccr_sub: String
    pl_fsaccr_cc: String
    pl_domain: String


}