import { BaseModel } from './base.model'

export class PurchaseOrder extends BaseModel {
    id: Number
    po_nbr: String
    po_category:String
    po_vend: String
    po_ship: String
    po_ord_date: String
    po_rmks: String
    po_cr_terms: String
    po_buyer: String
    po_shipvia: String
    po_fob: String
    po_bill: String
    po__qad04: Boolean
    po_partial: Boolean
    po_rev: Number
    po_stat: String
    po_ap_acct: String
    po_ap_cc: String
    po_frt: Number
    po_serv_chg: Number
    po_spec_chg: Number
    po_tax_pct: Number
    po_disc_pct: Number
    po_prepaid: Number
    po_contact: String
    po_confirm: Boolean
    po_cmtindx: Number
    po_print: Boolean
    po_cls_date: String
    po_taxable: Boolean
    po_user1: String
    po_user2: String
    po_curr: String
    po_ex_rate: Number
    po_lang: String
    po_fst_id: String
    po_pst_id: String
    po_pst: Boolean
    po_duty_type: String
    po__qad05: Number
    po__qad07: String
    po__qad08: String
    po_site: String
    po_blanket: String
    po__qad01: String
    po__qad02: Number
    po__qad03: String
    po_contract: String
    po_del_to: String
    po_due_date: String
    po_eff_strt: String
    po_eff_to: String
    po_est_value: Number
    po__qad06: Boolean
    po_project: String
    po_rel_nbr: Number
    po_req_id: String
    po_type: String
    po_user_id: String
    po__qad09: Number
    po_release: Boolean
    po_recurr: Boolean
    po_cycl: String
    po__chr01: String
    po__chr02: String
    po__chr03: String
    po__chr04: String
    po__chr05: String
    po__chr06: String
    po__chr07: String
    po__chr08: String
    po__chr09: String
    po__chr10: String
    po__dte01: String
    po__dte02: String
    po__dec01: Number
    po__dec02: Number
    po__log01: Boolean
    po_inv_mthd: String
    po_fix_rate: Boolean
    po_ent_ex: Number
    po_tax_date: String
    po_fsm_type: String
    po_bank: String
    po_pr_list: String
    po_tax_env: String
    po_sched: Boolean
    po_pr_list2: String
    po_tax_usage: String
    po_fix_pr: Boolean
    po_taxc: String
    po_sch_mthd: String
    po_priced_dt: String
    po_pricing_dt: String
    po_ers_opt: String
    po_pr_lst_tp: Number
    po__qadc01: String
    po__qadc02: String
    po__qadd01: Number
    po__qadd02: Number
    po__qadi01: Number
    po__qadi02: Number
    po_so_nbr: String
    po_is_btb: Boolean
    po_so_hold: Boolean
    po_xmit: String
    po_ex_rate2: Number
    po_ex_ratetype: String
    po_exru_seq: Number
    po_ap_sub: String
    po_crt_int: Number
    po_consignment: Boolean
    po_max_aging_days: Number
    po_app_owner: String
    po_tot_terms_code: String
    po_translt_days: Number

    po_amt: Number
    po_tax_amt: Number
    po_trl1_amt: Number

    po_domain: String
}