
import { BaseModel } from "./base.model"

export class Quote extends BaseModel {
    id: Number
    qo_nbr: String
    qo_cust: String
    qo_ship: String
    qo_ord_date: string
    qo_req_date: string
    qo_due_date: string
    qo_rmks: String
    qo_cr_terms: String
    qo_fob: String
    qo_po: String
    qo_shipvia: String
    qo_partial: Boolean
    qo_print_qo: Boolean
    qo_pr_list: String
    qo_xslspsn: String
    qo_source: String
    qo_xcomm_pc: Number
    qo_cr_card: String
    qo_print_pl: Boolean
    qo_cr_init: String
    qo_stat: String
    qo__qad01: Number
    qo__qad02: Number
    qo__qad03: Number
    qo_disc_pct: Number
    qo_tax_pct: Number
    qo_prepaid: Number
    qo_ar_acct: String
    qo_ar_cc: String
    qo_ship_date: string
    qo_taxable: Boolean
    qo__qad04: Number
    qo_user1: String
    qo_user2: String
    qo_so_nbr: String
    qo_confirm: string
    qo_exp_date: string
    qo_rel_date: string
    qo_relee: Boolean
    qo_recur: Boolean
    qo_cycle: String
    qo_rel_cnt: Number
    qo_flw_date: string
    qo_curr: String
    qo_ex_rate: Number
    qo_lang: String
    qo__qad05: Number
    qo_pst: Boolean
    qo_fst_id: String
    qo_pst_id: String
    qo_trl1_amt: Number
    qo_trl1_cd: String
    qo_trl2_amt: Number
    qo_trl2_cd: String
    qo_trl3_amt: Number
    qo_trl3_cd: String
    qo_weight: Number
    qo_weight_um: String
    qo_size: Number
    qo_size_um: String
    qo_cartons: Number
    qo_bol: String
    qo_site: String
    qo_taxc: String
    qo__chr01: String
    qo__chr02: String
    qo__chr03: String
    qo__chr04: String
    qo__chr05: String
    qo__chr06: String
    qo__chr07: String
    qo__chr08: String
    qo__chr09: String
    qo__chr10: String
    qo__dte01: string
    qo__dte02: string
    qo__dec01: Number
    qo__dec02: Number
    qo__log01: Boolean
    qo_project: String
    qo_rev: Number
    qo_pst_pct: Number
    qo_fr_list: String
    qo_fr_terms: String
    qo_comm_pct: Number
    qo_slspsn: String
    qo_fix_rate: Boolean
    qo_ent_ex: Number
    qo_bill: String
    qo_print_bl: Boolean
    qo_userid: String
    qo_tax_date: string
    qo_channel: String
    qo_inv_mthd: String
    qo_bank: String
    qo_fr_min_wt: Number
    qo_pr_list2: String
    qo_tax_env: String
    qo_tax_usage: String
    qo_priced_dt: string
    qo_pricing_dt: string
    qo_ex_rate2: Number
    qo_ex_ratetype: String
    qo_div: String
    qo_exru_seq: Number
    qo_ar_sub: String
    qo_app_owner: String
    qo_manual_fr_terms: Boolean
    qo_domain: String
    oid_qo_mstr: Number
}
