import { BaseModel } from "./base.model"

export class SaleShiper extends BaseModel{
    id: Number
    psh_nbr: String
    psh_line: number
    psh_part:  String
    psh_tax_code: String
    psh_ship_date: String
    psh_qty_ship: number
    psh_price: number
    psh_disc_pct: number
    psh_pur_cost: number
    psh_pur_std: number
    psh_shiper: String
    psh_cust: String
    psh_lot: String
    psh_ps_nbr: String
    psh_ps_qty: number
    psh_bo_qty: number
    psh_xinvoice: number
    psh_xinv_dt: String
    psh_xinv_cst: number
    psh_rev: String
    psh_type: String
    psh_print: boolean
    psh_invoiced: boolean
    psh_lbr_std: number
    psh_mtl_std: number
    psh_bdn_std: number
    psh_ovh_std: number
    psh_sub_std: number
    psh_buyer: String
    psh_shipto: String
    psh_cst_up: boolean
    psh_um: String
    psh_um_conv: number
    psh_curr: String
    psh_rmks: String
    psh_ex_rate: number
    psh_curr_amt: number
    psh_pay_um: String
    psh_user1: String
    psh_user2: String
    psh_site: String
    psh_loc: String
    psh_serial: String
    psh_ship: String
    psh_qty_ord: number
    psh_per_date: String
    psh_rcp_type: String
    psh_reason: String
    psh_request: String
    psh_approve: String
    psh_tax_at: String
    psh_rma_type: String
    psh_fix_rate: number
    psh_po_site: String
    psh_cum_req: number
    psh_cum_rcvd: number
    psh_fsm_type: String
    psh_bank: String
    psh_curr_rlse_id: String
    psh_cr_terms: String
    psh_element: number
    psh_fix_pr: boolean
    psh_so_taxable: boolean
    psh_taxable: boolean
    psh_crt_int: number
    psh_tax_env: String
    psh_tax_usage: String
    psh_tax_in: boolean
    psh_taxc: String
    psh_vend_lot: String
    psh_ex_rate2: number
    psh_ex_ratetype: String
    psh_exru_seq: number
    psh_domain: String   
    oid_psh_hist: number

}