
import { BaseModel } from "./base.model"

export class SaleOrder extends BaseModel {

    id: Number
    so_nbr: String
    so_cust: String
    so_ship: String
    so_category: String
    so_ord_date: String
    so_req_date: String
    so_due_date: String
    so_rmks: String
    so_cr_terms: String
    so_fob: String
    so_po: String
    so_shipvia: String
    so_partial: Boolean
    so_conf: Boolean
    so_print_so: Boolean
    so_inv_nbr: String
    so_pr_list: String
    so_xslspsn: String
    so_source: String
    so_xcomm_pct: Number
    so_cr_card: String
    so_print_pl: Boolean
    so_cr_init: String
    so_stat: String
    so__qad01: Number
    so__qad02: Number
    so__qad03: Number
    so_disc_pct: Number
    so_tax_pct: Number
    so_prepaid: Number
    so_to_inv: Boolean
    so_invoiced: Boolean
    so_ar_acct: String
    so_ar_cc: String
    so_inv_date: String
    so_ship_date: String
    so_taxable: Boolean
    so_cmtindx: Number
    so__qad04: Number
    so_user1: String
    so_user2: String
    so_curr: String
    so_ex_rate: Number
    so_lang: String
    so_type: String
    so_conf_date: String
    so_rev: Number
    so_bol: String
    so__qad05: Number
    so_pst: Boolean
    so_fst_id: String
    so_trl1_amt: Number
    so_trl1_cd: String
    so_trl2_amt: Number
    so_trl2_cd: String
    so_trl3_amt: Number
    so_trl3_cd: String
    so_weight: Number
    so_weight_um: String
    so_size: Number
    so_size_um: String
    so_cartons: Number
    so_site: String
    so_pst_id: String
    so_cncl_date: String
    so_quote: String
    so_taxc: String
    so__chr01: String
    so__chr02: String
    so__chr03: String
    so__chr04: String
    so__chr05: String
    so__chr06: String
    so__chr07: String
    so__chr08: String
    so__chr09: String
    so__chr10: String
    so__dte01: String
    so__dte02: String
    so__dec01: Number
    so__dec02: Number
    so__log01: Boolean
    so_credit: Boolean
    so_inv_cr: String
    so_project: String
    so_channel: String
    so_pst_pct: Number
    so_fr_list: String
    so_fr_terms: String
    so_slspsn: String
    so_comm_pct: Number
    so_inv_mthd: String
    so_fix_rate: Boolean
    so_ent_ex: Number
    so_bill: String
    so_print_bl: Boolean
    so_userid: String
    so_tax_date: String
    so_fsm_type: String
    so_conrep: String
    so_bank: String
    so_tax_env: String
    so_sched: Boolean
    so_fr_min_wt: Number
    so_pr_list2: String
    so_tax_usage: String
    so_sa_nbr: String
    so_fix_pr: Boolean
    so_sch_mthd: String
    so_pricing_dt: String
    so_priced_dt: String
    so_ca_nbr: String
    so_eng_code: String
    so_fcg_code: String
    so_ship_eng: Boolean
    so_crprlist: String
    so__qadc01: String
    so__qadc02: String
    so__qadc03: String
    so__qadc04: String
    so__qadc05: String
    so__qadl01: Boolean
    so__qadl02: Boolean
    so_incl_iss: Boolean
    so__qadi01: Number
    so__qadi02: Number
    so__qadi03: Number
    so__qadd01: Number
    so__qadd02: Number
    so__qadd03: Number
    so__qadt01: String
    so__qadt02: String
    so__qadt03: String
    so_auth_days: Number
    so_cum_acct: Boolean
    so_merge_rss: Boolean
    so_ship_cmplt: Number
    so_bump_all: Boolean
    so_primary: Boolean
    so_cust_po: String
    so_secondary: Boolean
    so_ship_po: String
    so_ex_rate2: Number
    so_ex_ratetype: String
    so_div: String
    so_exru_seq: Number
    so_app_owner: String
    so_ar_sub: String
    so_seq_order: Boolean
    so_inc_in_rss: Boolean
    so_firm_seq_days: Number
    so_prep_tax: Number
    so__qadl04: Boolean
    so_custref_val: Boolean
    so_consignment: Boolean
    so_max_aging_days: Number
    so_consign_loc: String
    so_intrans_loc: String
    so_auto_replenish: Boolean
    so_revenue: String
    so_fsaccr_acct: String
    so_fsaccr_sub: String
    so_fsaccr_cc: String
    so_fsdef_acct: String
    so_fsdef_sub: String
    so_fsdef_cc: String
    so_manual_fr_terms: Boolean
    so_domain: String
    oid_so_mstr: Number
    so_req_time: String
    so_amt: Number
    so_tax_amt : Number

}
