
import { BaseModel } from "./base.model"

export class Visite extends BaseModel {

    id: Number
    vis_nbr: String
    vis_cust: String
    vis_ship: String
    vis_category: String
    vis_ord_date: String
    vis_req_date: String
    vis_due_date: String
    vis_rmks: String
    vis_cr_terms: String
    vis_fob: String
    vis_po: String
    vis_shipvia: String
    vis_partial: Boolean
    vis_conf: Boolean
    vis_print_so: Boolean
    vis_inv_nbr: String
    vis_pr_list: String
    vis_xslspsn: String
    vis_source: String
    vis_xcomm_pct: Number
    vis_rsph: Number
    vis_rcyl: Number
    vis_radd: Number
    vis_rprisme: Number
    vis_rbase: Number
    vis_recart: Number
    vis_rhauteur: Number
    
    vis_raxe: Number

    vis_lsph: Number
    vis_lcyl: Number
    vis_ladd: Number
    vis_lprisme: Number
    vis_lbase: Number
    vis_lecart: Number
    vis_lhauteur: Number
    
    vis_laxe: Number
    vis_cr_card: String
    vis_print_pl: Boolean
    vis_cr_init: String
    vis_stat: String
    vis__qad01: Number
    vis__qad02: Number
    vis__qad03: Number
    vis_disc_pct: Number
    vis_tax_pct: Number
    vis_prepaid: Number
    vis_to_inv: Boolean
    vis_invoiced: Boolean
    vis_ar_acct: String
    vis_ar_cc: String
    vis_inv_date: String
    vis_ship_date: String
    vis_taxable: Boolean
    vis_cmtindx: Number
    vis__qad04: Number
    vis_user1: String
    vis_user2: String
    vis_curr: String
    vis_ex_rate: Number
    vis_lang: String
    vis_type: String
    vis_conf_date: String
    vis_rev: Number
    vis_bol: String
    vis__qad05: Number
    vis_pst: Boolean
    vis_fst_id: String
    vis_trl1_amt: Number
    vis_trl1_cd: String
    vis_trl2_amt: Number
    vis_trl2_cd: String
    vis_trl3_amt: Number
    vis_trl3_cd: String
    vis_weight: Number
    vis_weight_um: String
    vis_size: Number
    vis_size_um: String
    vis_cartons: Number
    vis_site: String
    vis_pst_id: String
    vis_cncl_date: String
    vis_quote: String
    vis_taxc: String
    vis__chr01: String
    vis__chr02: String
    vis__chr03: String
    vis__chr04: String
    vis__chr05: String
    vis__chr06: String
    vis__chr07: String
    vis__chr08: String
    vis__chr09: String
    vis__chr10: String
    vis__dte01: String
    vis__dte02: String
    vis__dec01: Number
    vis__dec02: Number
    vis__log01: Boolean
    vis_credit: Boolean
    vis_inv_cr: String
    vis_project: String
    vis_channel: String
    vis_pst_pct: Number
    vis_fr_list: String
    vis_fr_terms: String
    vis_slspsn: String
    vis_comm_pct: Number
    vis_inv_mthd: String
    vis_fix_rate: Boolean
    vis_ent_ex: Number
    vis_bill: String
    vis_print_bl: Boolean
    vis_userid: String
    vis_tax_date: String
    vis_fsm_type: String
    vis_conrep: String
    vis_bank: String
    vis_tax_env: String
    vis_sched: Boolean
    vis_fr_min_wt: Number
    vis_pr_list2: String
    vis_tax_usage: String
    vis_sa_nbr: String
    vis_fix_pr: Boolean
    vis_sch_mthd: String
    vis_pricing_dt: String
    vis_priced_dt: String
    vis_ca_nbr: String
    vis_eng_code: String
    vis_fcg_code: String
    vis_ship_eng: Boolean
    vis_crprlist: String
    vis__qadc01: String
    vis__qadc02: String
    vis__qadc03: String
    vis__qadc04: String
    vis__qadc05: String
    vis__qadl01: Boolean
    vis__qadl02: Boolean
    vis_incl_iss: Boolean
    vis__qadi01: Number
    vis__qadi02: Number
    vis__qadi03: Number
    vis__qadd01: Number
    vis__qadd02: Number
    vis__qadd03: Number
    vis__qadt01: String
    vis__qadt02: String
    vis__qadt03: String
    vis_auth_days: Number
    vis_cum_acct: Boolean
    vis_merge_rss: Boolean
    vis_ship_cmplt: Number
    vis_bump_all: Boolean
    vis_primary: Boolean
    vis_cust_po: String
    vis_secondary: Boolean
    vis_ship_po: String
    vis_ex_rate2: Number
    vis_ex_ratetype: String
    vis_div: String
    vis_exru_seq: Number
    vis_app_owner: String
    vis_ar_sub: String
    vis_seq_order: Boolean
    vis_inc_in_rss: Boolean
    vis_firm_seq_days: Number
    vis_prep_tax: Number
    vis__qadl04: Boolean
    vis_custref_val: Boolean
    vis_consignment: Boolean
    vis_max_aging_days: Number
    vis_consign_loc: String
    vis_intrans_loc: String
    vis_auto_replenish: Boolean
    vis_revenue: String
    vis_fsaccr_acct: String
    vis_fsaccr_sub: String
    vis_fsaccr_cc: String
    vis_fsdef_acct: String
    vis_fsdef_sub: String
    vis_fsdef_cc: String
    vis_manual_fr_terms: Boolean
    vis_domain: String
    oid_vis_mstr: Number
    vis_req_time: String
    vis_amt: Number
    vis_tax_amt : Number

}
